# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(261F2E)
$foreground = rgb(E0DAFB)
$color0 = rgb(4D4456)
$color1 = rgb(230750)
$color2 = rgb(260D51)
$color3 = rgb(531CA0)
$color4 = rgb(544187)
$color5 = rgb(7769B0)
$color6 = rgb(7D70B7)
$color7 = rgb(CAC2F1)
$color8 = rgb(8D87A9)
$color9 = rgb(2F0A6A)
$color10 = rgb(33116C)
$color11 = rgb(6F25D5)
$color12 = rgb(7057B5)
$color13 = rgb(9E8CEB)
$color14 = rgb(A695F4)
$color15 = rgb(CAC2F1)
