# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111111)
$foreground = rgb(EEE9E3)
$color0 = rgb(393939)
$color1 = rgb(0C0D0E)
$color2 = rgb(0F0E0F)
$color3 = rgb(3C201D)
$color4 = rgb(43231F)
$color5 = rgb(6E564F)
$color6 = rgb(9B8F83)
$color7 = rgb(DED7CF)
$color8 = rgb(9B9691)
$color9 = rgb(101112)
$color10 = rgb(151313)
$color11 = rgb(502B26)
$color12 = rgb(592F29)
$color13 = rgb(937269)
$color14 = rgb(CEBFAF)
$color15 = rgb(DED7CF)
