# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1211)
$foreground = rgb(DCDCDC)
$color0 = rgb(433939)
$color1 = rgb(230301)
$color2 = rgb(6E1B21)
$color3 = rgb(3B3B3B)
$color4 = rgb(714D4F)
$color5 = rgb(736E6E)
$color6 = rgb(737474)
$color7 = rgb(C4C4C4)
$color8 = rgb(898989)
$color9 = rgb(2F0402)
$color10 = rgb(92242C)
$color11 = rgb(4F4F4F)
$color12 = rgb(96666A)
$color13 = rgb(999393)
$color14 = rgb(9A9A9A)
$color15 = rgb(C4C4C4)
