# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E0DAFB
background         #261F2E
cursor             #8975B4

active_tab_foreground     #261F2E
active_tab_background     #E0DAFB
inactive_tab_foreground   #E0DAFB
inactive_tab_background   #261F2E

active_border_color   #E0DAFB
inactive_border_color #261F2E
bell_border_color     #230750

color0      #4D4456
color1		#230750
color2		#260D51
color3		#531CA0
color4		#544187
color5		#7769B0
color6		#7D70B7
color7		#CAC2F1
color8		#8D87A9
color9		#2F0A6A
color10		#33116C
color11		#6F25D5
color12		#7057B5
color13		#9E8CEB
color14		#A695F4
color15		#CAC2F1
