# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EEE9E3
background         #111111
cursor             #817E7B

active_tab_foreground     #111111
active_tab_background     #EEE9E3
inactive_tab_foreground   #EEE9E3
inactive_tab_background   #111111

active_border_color   #EEE9E3
inactive_border_color #111111
bell_border_color     #0C0D0E

color0      #393939
color1		#0C0D0E
color2		#0F0E0F
color3		#3C201D
color4		#43231F
color5		#6E564F
color6		#9B8F83
color7		#DED7CF
color8		#9B9691
color9		#101112
color10		#151313
color11		#502B26
color12		#592F29
color13		#937269
color14		#CEBFAF
color15		#DED7CF
